# Generated by Django 2.2 on 2020-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mystudent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='mystudent',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Accept'),
        ),
    ]
