# Generated by Django 2.2 on 2020-05-31 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200530_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Ignore'),
        ),
        migrations.AlterField(
            model_name='mystudent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
