# Generated by Django 2.2 on 2020-06-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200531_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myteacher',
            name='batch_name',
        ),
    ]
