# Generated by Django 2.2 on 2020-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200626_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudent',
            name='class_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
