# Generated by Django 2.2 on 2020-07-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_mystudent_class_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myteacher',
            options={'verbose_name': 'Verification Code'},
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='Exam Player', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Verification Code'),
        ),
    ]
