# Generated by Django 2.2 on 2020-05-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='right_answer',
            field=models.FloatField(default=969.0),
        ),
        migrations.AddField(
            model_name='gradedassignment',
            name='total_marks',
            field=models.FloatField(default=969.0),
        ),
    ]
