# Generated by Django 2.2 on 2020-05-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200509_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='obtained_marks',
            field=models.FloatField(default=969.0),
        ),
    ]
