# Generated by Django 2.2 on 2020-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gradedassignment_obtained_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_hide',
            field=models.BooleanField(default=True),
        ),
    ]
