# Generated by Django 2.2 on 2020-05-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200510_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
