# Generated by Django 2.2 on 2020-05-10 22:15

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gradedassignment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='date_time',
            field=api.models.CustomDateTimeField(auto_now=True, null=True),
        ),
    ]
