# Generated by Django 2.2 on 2020-05-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200510_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='time_in_min',
            field=models.IntegerField(default=2000, null=True),
        ),
    ]
