# Generated by Django 2.2 on 2020-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_assignment_time_in_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='time_in_min',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
