# Generated by Django 2.2 on 2020-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200514_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='time_in_min',
            field=models.IntegerField(null=True),
        ),
    ]
