# Generated by Django 2.2 on 2020-05-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200514_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Exam'},
        ),
        migrations.AlterModelOptions(
            name='gradedassignment',
            options={'verbose_name': 'Result'},
        ),
    ]
