# Generated by Django 2.2 on 2020-05-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choices',
            new_name='choice',
        ),
    ]
