# Generated by Django 2.2 on 2020-05-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200531_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice',
            new_name='choices',
        ),
    ]
