# Generated by Django 2.2 on 2020-06-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200531_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Question'),
        ),
    ]
