# Generated by Django 2.2 on 2020-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200602_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
