# Generated by Django 2.2 on 2020-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_assignment_negative_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_hide',
            field=models.BooleanField(default=True, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='negative_marking',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
